config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :films do
    member do
      post :join
      post :quit
    end


    resources :posts
  end
  root 'films#index'


namespace :account do
  resources :films
  resources :posts
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user
  has_many :posts
  validates :title, presence: true

  has_many :films_relationships
  has_many :member, through: :film_relationship, source: :user
end

app/models/film_relationship.rb
class FilmRelationship < ApplicationRecord
  belongs_to :film
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :film

  scope :recent,   -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :films
  has_many :posts

  has_many :film_relationships
  has_many :participated_films, :through => :film_relationships, :source => :film

  def is_member_of?(film)
    participated_films.include?(film)
  end

  def join!(film)
    participated_films << film
  end

  def quit!(film)
    participated_films.delete(film)
  end
end

app/controllers/account/films_controller.rb
class Account::FilmsController < ApplicationController
  before_action :authenticate_user!
  def index
    @films = current_user.participated_films
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = current_user.posts
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authenticate_user! ,only: [:new, :create, :edit, :destroy, :update]
  before_action :find_film_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @films = Film.all
  end

  def show
    @film = Film.find(params[:id])
    @posts = @film.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    @film.user = current_user
    if @film.save
      current_user.join!(@film)
      redirect_to films_path
    else
      render :new
    end
  end

  def destroy
    @film.destroy
    flash[:alert] = "Film deleted"
    redirect_to films_path
  end

  def update
   if @film.update(film_params)
     redirect_to films_path, notice: "Update Success"
   else
     render :edit
   end
  end


  def join
    @film = Film.find(params[:id])

    if !current_user.is_member_of?(@film)
      current_user.join!(@film)
      flash[:notice] = "恭喜你，收藏成功！"
    else
      flash[:warning] = "你已经收藏该影片了！"
    end

    redirect_to film_path(@film)
    end

    def quit
      @film= Film.find(params[:id])

      if current_user.is_member_of?(@film)
        current_user.quit!(@film)
        flash[:alert] = "已取消收藏！"
      else
        flash[:warning] = "你未收藏该电影"
      end

      redirect_to film_path(@film)
    end

  private

  def find_film_and_check_permission
    @film = Film.find(params[:id])
    if current_user != @film.user
      redirect_to root_path, alert: "你没有权限执行此操作！"
    end
  end

  def film_params
    params.require(:film).permit(:title, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @film = Film.find(params[:film_id])
    @post = Post.new
  end

  def create
    @film = Film.find(params[:film_id])
    @post = Post.new(post_params)
    @post.film = @film
    @post.user = current_user

    if @post.save
      redirect_to film_path(@film)
    else
      render :new
    end
  end

  def edit
    @film = Film.find(params[:film_id])
    @post = Post.find(params[:id])
  end

  def update
    @film = Film.find(params[:film_id])
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to account_posts_path(@film), notice: 'Post Update Success!'
    else
      render :edit
    end
  end

  def destroy
    @film = Film.find(params[:film_id])
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to account_posts_path(@film), alert: 'Post deleted!'
    else
     render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @film = Film.find(params[:film_id])
    @review = Review.new
  end

  def create
    @film = Film.find(params[:film_id])
    @review = Review.new(review_params)
    @review.Film=@film
    @review.user = current_user

    if @review.save
      redirect_to film_path(@film)
    else
      render :new
    end
  end


  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/helpers/account/films_helper.rb
module Account::FilmsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
  def render_film_description(film)
    simple_format(film.description)
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
 <% user_facing_flashes.each do |key, value| %>
  <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= value %>
  </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright @2017 Moive
     <br>Design by
     <a href="http://courses.growthschool.com/courses/rails101/" target=_new>xdite</a>
   </p>
 </footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/"> Moive</a>
    </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %> </li>
          <li><%= link_to("登录", new_user_session_path) %> </li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hi!, <%= current_user.email %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li> <%= link_to("我的电影", account_films_path) %></li>
                <li> <%= link_to("我的评论", account_posts_path) %></li>
                <li class=“divider”> </li>

                <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
              </ul>
            </li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>

app/views/common/flashes.html.erb
<% if flash.any? %>
 <% user_facing_flashes.each do |key, value| %>
  <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= value %>
  </div>
  <% end %>
<% end %>

app/views/films/_film_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(film.title, film_path(film)) %></td>
  <td><%= render_film_description(film) %></td>
  <td><%= film.user.email %></td>
  <td>
    <% if current_user && current_user == film.user %>
     <%= link_to("编辑", edit_film_path(film), class: "btn btn-sm btn-default")%>
     <%= link_to("删除", film_path(film),           class: "btn btn-sm btn-default",
                 method: :delete, data: { confirm: "确定删除吗" }  )%>
    <% end %>
  </td>
</tr>

app/views/films/_form.html.erb
<%= simple_form_for @film do |f| %>
 <div class="form-film">
    <%= f.input :title, label:'片名', input_html: { class: "form-control"} %>
   <%= f.input :description, label: '简述', input_html: { class: "form-control"} %>
 </div>
 <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
 <% end %>

app/views/films/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑电影名</h2>

  <hr>
 <%= render "form" %>



</div>

app/views/films/index.html.erb
<div class="col-md-12">
  <div class="film">
    <%= link_to("New film", new_film_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>影名</td>
        <td>电影描述</td>
        <td>创建者</td>
      </tr>
    </thead>
    <tbody>
    <%= render :partial => "film_item", :collection => @films, :as => :film %>
  </tbody>
</table>
</div>

app/views/films/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>添加电影</h2>

  <hr>
  <%= render "form" %>


</div>

app/views/films/show.html.erb
<div class="col-md-12">
  <div class="film">

    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@film) %>
        <label class="label label-success"> 收藏</label>
              <%= link_to("取消收藏", quit_film_path(@film), method: :post, class: "btn btn-default") %>
        <% else %>
        <label class="label label-warning"> 未收藏</label>
        <%= link_to("点我收藏",join_film_path(@film), method: :post, class: "btn btn-default") %>
        <% end %>
      </span>

     <%= link_to("写评论", new_film_post_path(@film), class: "btn btn-default pull-right")%>
    <% if current_user && current_user == @film.user %>
    <%= link_to("编辑", edit_film_path(@film), class: "btn btn-primary pull-right")%>
    <% end %>
  </div>
   <h2><%= @film.title %></h2>
   <p><%= @film.description %></p>

  <table class="table">
    <thead>
     <tr>
        <th>评论</th>
        <th>评论者</th>
       <th>发表时间</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.content %></td>
          <td><%= post.user.email %></td>
          <td><%= post.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @posts %>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moive</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
              <%= render "common/navbar" %>
              <%= render "common/flashes" %>
              <%= yield %>
          </div>

          <%= render "common/footer" %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for [@film, @post] do |f| %>

<div class="form-post">
  <%= f.input :content, input_html: {class: "form-control"} %>
</div>
<%= f.submit "Submit", class:"btn btn-primary", data: {disable_with: "Submitting..."} %>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑评论</h2>
  <hr>
  <%= render "form" %>
</div>

app/views/posts/new.html.erb
<h2 class="text-center">评论</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@film,@post] do |f| %>
    <div class="form-film">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1> Hello </h1>